name = "PySA"
uuid = "46b73cfa-376a-48ee-8926-0c45ac3f7830"
authors = ["pedromxavier <pedromxavier@psr-inc.com>"]
version = "0.1.0"

[deps]
Anneal = "e4d9eb7f-b088-426e-aeb5-1c0dae3d8abb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
